# Generated by Django 4.1.2 on 2024-06-28 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Innova', '0002_quienesomo_servicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quienesomo',
            name='descripcion_quienesomos',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='descripcion_servicio',
            field=models.CharField(max_length=200),
        ),
    ]
