# Generated by Django 4.1.2 on 2024-06-28 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Innova', '0004_alter_quienesomo_descripcion_quienesomos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quienesomo',
            name='titulo_quienesomos',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='titulo_servicio',
            field=models.CharField(max_length=30),
        ),
    ]
