# Generated by Django 4.1.2 on 2024-06-29 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Innova', '0005_alter_quienesomo_titulo_quienesomos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quienesomo',
            name='titulo_quienesomos',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='titulo_servicio',
            field=models.CharField(max_length=50),
        ),
    ]
