# Generated by Django 4.1.2 on 2024-06-29 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Innova', '0006_alter_quienesomo_titulo_quienesomos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quienesomo',
            name='imagen',
            field=models.ImageField(null=True, upload_to='innova'),
        ),
    ]
